name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver type of new version"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - premajor
          - preminor
          - prepatch
          - prerelease

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      # Check out the content (source branch).  Use a deploy key so that
      # when we push changes, it will trigger the release workflow
      # run that runs on: tag. (Using the GitHub token would
      # not run the workflow to prevent infinite recursion.)
      - name: Check out source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_tag_gpgsign: true

      - name: Bump version and create tag
        run: |
          pip install dunamai
          dunamai from any
          poetry self add "poetry-dynamic-versioning[plugin]"        
          ver=v$(poetry version ${{ github.event.inputs.version }} --short)
          now="$(date +'%Y.%m.%d')"
          git tag -s -a $ver -m "$ver ($now)"
          git push origin $ver
