name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      # TODO: use dunamai to get version from tag

      - uses: actions/checkout@v4
        with:
          # This is necessary so that we have the tags.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Get release version from tag
        uses: mtkennerly/dunamai-action@v1
        with:
          env-var: VERSION
          args: --style semver

      - name: Write _version.py file
        run: echo "__version__ = \"$VERSION\"" > src/disposition/_version.py

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Build package
        run: poetry build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  create-github-release:
    name: Create GitHub Release
    # NOTE: include package distribution here

    runs-on: ubuntu-latest
    needs: publish-to-pypi
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
