name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Get release version from tag
        uses: mtkennerly/dunamai-action@v1
        with:
          env-var: VERSION
          args: --style semver

      - name: Write _version.py file
        run: |
          echo "Version: $VERSION"
          echo "__version__ = \"$VERSION\"" > src/disposition/_version.py

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Build package
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build-package
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish-to-pypi
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/

      - name: Create Release
        run: |
          gh release create ${{ github.ref }} --generate-notes
          gh release upload ${{ github.ref }} dist/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
